### ISSUE TITLE
Request to create ontap event

### ISSUE THREAD

**Issue by Leoudayan** [timcreatedit/body_part_selector#2]
Hi,

The Body Part Selector you created is really helpful for my research and I wanted to ask if you could create a way to easily write ontap event. I want to do certain actions for each part. It will be great if you could please implement this change. Please let me know if this can be done in the existing project. 

Thanks!
Mano

**Comment by marwaneldesouki** [comment]
there is no events but actually you can use the _bodyparts as a flag to your function 
correct ?

**Comment by timcreatedit** [comment]
Hello there! Can you tell me which usecase isn't covered by the `onSelectionUpdated` callback? Any state change should be covered by this, so I'll close this issue, but I'll reopen if you have more information that I'm not seeing :)
